Repository interactions-py/interactions.py, pull requests merged in 2021-03, with the labels that each got.

#109 Fixed minor spelling mistake
  docs/faq.rst
Labels: documentation

#122 Update manage_commands.py
  discord_slash/utils/manage_commands.py
Labels: pending

#131 Fix spelling mistakes
  .github/PULL_REQUEST_TEMPLATE.md
  discord_slash/client.py
  discord_slash/context.py
  docs/migration.rst
Labels: breaking, pending
