Repository interactions-py/interactions.py, pull requests merged in 2021-06, with the labels that each got.

#197 Fix issue where default_permission doesn't get updated on sync.
  discord_slash/model.py
Labels: bug, priority

#199 Fix manage commands
  discord_slash/utils/manage_commands.py
Labels: bug, priority

#179 Polished up readme
  README.md
Labels: documentation

#162 General cleanup and format code with black
  .flake8
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .gitignore
  README.md
  discord_slash/__init__.py
  discord_slash/client.py
  discord_slash/cog_ext.py
  discord_slash/const.py
  discord_slash/context.py
  discord_slash/dpy_overrides.py
  discord_slash/error.py
  discord_slash/http.py
  discord_slash/model.py
  discord_slash/utils/manage_commands.py
  discord_slash/utils/manage_components.py
  docs/_static/scope.jpg
  docs/conf.py
  docs/quickstart.rst
  pre_push.py
  pyproject.toml
  readthedocs.yml
  requirements.txt
  setup.py
Labels: enhancement, pending

#204 Futher improvements in components implementation
  discord_slash/__init__.py
  discord_slash/context.py
  discord_slash/dpy_overrides.py
  discord_slash/model.py
  discord_slash/utils/manage_components.py
Labels: enhancement, pending
