Repository interactions-py/interactions.py, pull requests merged in 2021-05, with the labels that each got.

#156 Add Application Permissions Support
  discord_slash/client.py
  discord_slash/cog_ext.py
  discord_slash/http.py
  discord_slash/model.py
  discord_slash/utils/manage_commands.py
  docs/gettingstarted.rst
Labels: enhancement, priority

#176 Permission fixes
  discord_slash/client.py
  discord_slash/cog_ext.py
  discord_slash/model.py
  docs/gettingstarted.rst
Labels: documentation

#165 Updated The Sync_Commands=True
  README.md
Labels: documentation

#174 Fix eunwoo1104/discord-py-slash-command#173
  discord_slash/model.py
Labels: bug
