Repository interactions-py/interactions.py, pull requests merged in 2021-08, with the labels that each got.

#293 Reorder type listening + Menu/SlashContext confusion
  discord_slash/client.py
Labels: bug, specific condition, priority

#276 Fix Python 3.8 Union type checking.
  discord_slash/model.py
Labels: enhancement

#297 Context menu example to README + indentation 4 spaces
  README.md
  docs/gettingstarted.rst
Labels: documentation
