Repository interactions-py/interactions.py, pull requests merged in 2021-07, with the labels that each got.

#243 Select Support
  discord_slash/context.py
  discord_slash/utils/manage_components.py
  docs/components.rst
Labels: documentation, enhancement, priority

#255 Fix KeyError in ComponentContext
  discord_slash/context.py
Labels: pending

#261 Fixed cmd_name parameter description.
  discord_slash/http.py
  discord_slash/utils/manage_commands.py
  docs/faq.rst
Labels: documentation, pending

#262 Introduction to some d.py Aliases
  discord_slash/context.py
Labels: pending
