Repository interactions-py/interactions.py, pull requests merged in 2022-09, with the labels that each got.

#1026 refactor: Enable repr for all models
  interactions/api/models/channel.py
  interactions/api/models/emoji.py
  interactions/api/models/guild.py
  interactions/api/models/member.py
  interactions/api/models/message.py
  interactions/api/models/role.py
  interactions/api/models/team.py
  interactions/api/models/user.py
  interactions/api/models/webhook.py
  interactions/utils/attrs_utils.py
Labels: enhancement, priority

#1070 fix: Fix constant gateway resume/invalid session loop.
  interactions/api/gateway/client.py
Labels: bug

#1076 fix: warn for no app cmd scope for disable_sync
  interactions/client/bot.py
Labels: bug

#766 feat: Implement barebones Forum channel support.
  interactions/api/http/channel.py
  interactions/api/http/thread.py
  interactions/api/models/channel.py
  interactions/api/models/gw.py
Labels: documentation, enhancement

#1083 feat: Utilise reconnection lock for packet sending.
  interactions/api/gateway/client.py
Labels: bug

#1103 fix: autodefer erroring when `*args` is empty
  interactions/utils/utils.py
Labels: bug
