Repository interactions-py/interactions.py, pull requests merged in 2022-07, with the labels that each got.

#908 refactor: Refactor context edit/send/defer.
  interactions/client/context.py
Labels: enhancement, help wanted

#895 feat: merge enhanced
  docs/migration.rst
  docs/models.rst
  docs/models.utils.rst
  docs/quickstart.rst
  interactions/api/dispatch.py
  interactions/api/http/client.py
  interactions/api/http/limiter.py
  interactions/api/http/request.py
  interactions/api/models/attrs_utils.py
  interactions/client/bot.py
  interactions/client/models/__init__.py
  interactions/client/models/command.py
  interactions/client/models/component.py
  interactions/client/models/utils.py
Labels: documentation, enhancement

#801 feat: implement ``get`` function
  docs/api.rst
  docs/get.rst
  docs/migration.rst
  interactions/client/__init__.py
  interactions/client/get.py
  interactions/client/get.pyi
Labels: documentation, enhancement

#922 chore: version bump
  interactions/base.py
Labels: pending, priority

#935 feat: Remove PresenceButton object.
  interactions/api/models/presence.py
Labels: bug

#931 docs: document `on_start` in more places
  docs/migration.rst
  interactions/api/gateway/client.py
Labels: documentation

#936 docs: Add question tags to type descriptors in docstrings
  interactions/api/dispatch.py
  interactions/api/gateway/client.py
  interactions/api/http/request.py
  interactions/api/http/route.py
  interactions/api/models/channel.py
  interactions/api/models/guild.py
  interactions/api/models/gw.py
  interactions/api/models/member.py
  interactions/api/models/message.py
  interactions/api/models/role.py
  interactions/api/models/webhook.py
  interactions/client/bot.py
  interactions/client/context.py
  interactions/client/models/command.py
  interactions/client/models/utils.py
  interactions/ext/base.py
  interactions/ext/version.py
Labels: documentation

#947 fix: Fix item assign error dynamically.
  interactions/api/models/attrs_utils.py
Labels: bug

#952 feat: Add audit log object
  docs/api.models.audit_log.rst
  docs/api.models.rst
  interactions/api/models/__init__.py
  interactions/api/models/audit_log.py
  interactions/api/models/guild.py
Labels: documentation, enhancement, priority

#958 fix: SyntaxError from the last PR
  interactions/api/models/guild.py
Labels: bug

#949 feat: on_command_error event
  docs/events.rst
  interactions/client/bot.py
  interactions/client/models/command.py
Labels: documentation, enhancement

#950 feat!: smarter option decorator
  docs/migration.rst
  docs/quickstart.rst
  interactions/client/models/command.py
Labels: documentation, enhancement, breaking

#961 fix: nested options and choices
  interactions/client/models/command.py
Labels: bug, priority

#962 fix: `ActionRow.new()` typehinting
  interactions/client/models/component.py
Labels: bug

#967 feat: Suppress voice state console logs.
  interactions/api/gateway/client.py
Labels: enhancement

#960 chore: version bump
  interactions/base.py
Labels: pending, priority

#970 fix: fix some bugs with cache
  interactions/api/gateway/client.py
  interactions/api/models/gw.py
Labels: bug

#984 chore: Version bump
  interactions/base.py
Labels: priority

#985 chore: Merge unstable to stable
  interactions/api/gateway/client.py
  interactions/api/http/emoji.py
  interactions/api/http/invite.py
  interactions/api/http/member.py
  interactions/api/http/request.py
  interactions/api/models/__init__.py
  interactions/api/models/attrs_utils.py
  interactions/api/models/emoji.py
  interactions/api/models/guild.py
  interactions/api/models/gw.py
  interactions/api/models/message.py
  interactions/api/models/presence.py
  interactions/base.py
  interactions/client/get.py
  interactions/client/get.pyi
  interactions/client/models/component.py
  interactions/client/models/misc.py
Labels: priority
