Repository interactions-py/interactions.py, pull requests merged in 2022-08, with the labels that each got.

#999 fix: Remove empty _client attribute in _json property
  interactions/api/models/attrs_utils.py
Labels: bug

#969 feat: Add member and channel permissions calculation functions
  interactions/api/models/channel.py
  interactions/api/models/flags.py
  interactions/api/models/member.py
Labels: enhancement

#1022 feat!: Completely redo gateway process.
  interactions/api/gateway/__init__.py
  interactions/api/gateway/client.py
  interactions/api/gateway/ratelimit.py
  interactions/api/models/presence.py
  interactions/client/bot.py
Labels: bug, enhancement, breaking, priority

#1014 refactor(bot, gateway, http): Remove any unclosed client session messages
  interactions/api/gateway/client.py
  interactions/api/http/request.py
  interactions/client/bot.py
Labels: documentation, enhancement, priority
