Repository interactions-py/interactions.py, pull requests merged in 2022-06, with the labels that each got.

#811 docs: fix incorrect type note for Overwrite id
  interactions/api/models/misc.py
  interactions/api/models/misc.pyi
Labels: documentation

#813 fix: Fix autocompletion parsing past the first option.
  interactions/api/gateway/client.py
Labels: bug

#814 refactor!: Change function naming, add a `None`-Type check for reactions
  interactions/api/models/member.py
  interactions/api/models/member.pyi
  interactions/api/models/message.py
Labels: bug, breaking

#810 feat!: make the library use `__all__` to not alias every import from another library
  interactions/api/cache.py
  interactions/api/dispatch.py
  interactions/api/enums.py
  interactions/api/error.py
  interactions/api/gateway/client.py
  interactions/api/gateway/heartbeat.py
  interactions/api/http/channel.py
  interactions/api/http/client.py
  interactions/api/http/emoji.py
  interactions/api/http/guild.py
  interactions/api/http/interaction.py
  interactions/api/http/limiter.py
  interactions/api/http/member.py
  interactions/api/http/message.py
  interactions/api/http/reaction.py
  interactions/api/http/request.py
  interactions/api/http/route.py
  interactions/api/http/scheduledEvent.py
  interactions/api/http/sticker.py
  interactions/api/http/thread.py
  interactions/api/http/user.py
  interactions/api/http/webhook.py
  interactions/api/models/channel.py
  interactions/api/models/flags.py
  interactions/api/models/guild.py
  interactions/api/models/gw.py
  interactions/api/models/member.py
  interactions/api/models/message.py
  interactions/api/models/misc.py
  interactions/api/models/presence.py
  interactions/api/models/role.py
  interactions/api/models/team.py
  interactions/api/models/user.py
  interactions/api/models/webhook.py
  interactions/base.py
  interactions/client/bot.py
  interactions/client/context.py
  interactions/client/decor.py
  interactions/client/enums.py
  interactions/client/models/command.py
  interactions/client/models/component.py
  interactions/client/models/misc.py
  interactions/ext/base.py
  interactions/ext/converter.py
  interactions/ext/error.py
  interactions/ext/version.py
Labels: bug, enhancement, breaking

#795 refactor!: migration to use attrs on the majority of models
  interactions/api/gateway/client.py
  interactions/api/gateway/client.pyi
  interactions/api/gateway/heartbeat.pyi
  interactions/api/http/channel.py
  interactions/api/http/channel.pyi
  interactions/api/http/client.pyi
  interactions/api/http/emoji.pyi
  interactions/api/http/guild.py
  interactions/api/http/guild.pyi
  interactions/api/http/interaction.pyi
  interactions/api/http/invite.pyi
  interactions/api/http/limiter.pyi
  interactions/api/http/member.pyi
  interactions/api/http/message.py
  interactions/api/http/message.pyi
  interactions/api/http/reaction.pyi
  interactions/api/http/request.pyi
  interactions/api/http/route.pyi
  interactions/api/http/scheduledEvent.pyi
  interactions/api/http/sticker.pyi
  interactions/api/http/thread.pyi
  interactions/api/http/user.pyi
  interactions/api/http/webhook.pyi
  interactions/api/models/attrs_utils.py
  interactions/api/models/attrs_utils.pyi
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
  interactions/api/models/gw.py
  interactions/api/models/gw.pyi
  interactions/api/models/member.py
  interactions/api/models/member.pyi
  interactions/api/models/message.py
  interactions/api/models/message.pyi
  interactions/api/models/misc.py
  interactions/api/models/misc.pyi
  interactions/api/models/presence.py
  interactions/api/models/presence.pyi
  interactions/api/models/role.py
  interactions/api/models/role.pyi
  interactions/api/models/team.py
  interactions/api/models/team.pyi
  interactions/api/models/user.py
  interactions/api/models/user.pyi
  interactions/api/models/webhook.py
  interactions/api/models/webhook.pyi
  interactions/client/bot.py
  interactions/client/bot.pyi
  interactions/client/context.py
  interactions/client/context.pyi
  interactions/client/decor.pyi
  interactions/client/models/command.py
  interactions/client/models/component.py
  interactions/client/models/misc.py
  interactions/ext/base.pyi
Labels: breaking

#828 refactor!: Improve DX with allowing the usage of the actual object additionally to the ID
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
  interactions/api/models/member.py
  interactions/api/models/member.pyi
  interactions/api/models/message.py
  interactions/api/models/message.pyi
  interactions/api/models/role.py
  interactions/api/models/role.pyi
Labels: enhancement, breaking

#858 chore: bump version to 4.3 beta
  interactions/base.py
Labels: on hold

#874 fix: message from ComponentContext.edit has missing attributes
  interactions/client/context.py
Labels: bug

#882 fix: Fix option/choice order sync, redo _pos calculation.
  interactions/client/bot.py
Labels: bug

#885 refactor!: Change `Color` class' colors from properties to
  interactions/api/models/misc.py
  interactions/api/models/misc.pyi
Labels: breaking

#886 docs: Repoint old rtd links to new domain.
  README.rst
  docs/quickstart.rst
Labels: documentation

#897 feat: Implement app_permissions attribute to Context.
  interactions/client/context.py
  interactions/client/context.pyi
Labels: enhancement
