Repository interactions-py/interactions.py, pull requests merged in 2022-05, with the labels that each got.

#763 fix: Fix client presence Unix time calculation.
  interactions/api/models/presence.py
Labels: bug, priority

#771 fix: Fix per-route ratelimit call-later implementation.
  interactions/api/http/request.py
Labels: bug, priority

#772 fix: Fix autocomplete parsing on more than 1 argument.
  interactions/api/gateway/client.py
Labels: bug

#773 fix: Fix dictionary iteration on method.
  interactions/api/http/channel.py
Labels: bug, priority

#758 feat: implement channel.get_history
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
Labels: documentation, enhancement

#775 fix: Fix not present client on function return
  interactions/api/models/message.py
Labels: bug

#765 feat!: Implement barebones v2 permissions.
  docs/locale/de/LC_MESSAGES/api.http.po
  docs/locale/de/LC_MESSAGES/api.models.channel.po
  docs/locale/de/LC_MESSAGES/api.models.guild.po
  docs/locale/de/LC_MESSAGES/api.models.message.po
  docs/locale/fr/LC_MESSAGES/api.http.po
  docs/locale/fr/LC_MESSAGES/api.models.channel.po
  docs/locale/fr/LC_MESSAGES/api.models.guild.po
  docs/locale/fr/LC_MESSAGES/api.models.message.po
  docs/locale/hi/LC_MESSAGES/api.http.po
  docs/locale/hi/LC_MESSAGES/api.models.channel.po
  docs/locale/hi/LC_MESSAGES/api.models.guild.po
  docs/locale/hi/LC_MESSAGES/api.models.message.po
  docs/locale/it/LC_MESSAGES/api.http.po
  docs/locale/it/LC_MESSAGES/api.models.channel.po
  docs/locale/it/LC_MESSAGES/api.models.guild.po
  docs/locale/it/LC_MESSAGES/api.models.message.po
  docs/locale/pl/LC_MESSAGES/api.http.po
  docs/locale/pl/LC_MESSAGES/api.models.channel.po
  docs/locale/pl/LC_MESSAGES/api.models.guild.po
  docs/locale/pl/LC_MESSAGES/api.models.message.po
  docs/locale/ru/LC_MESSAGES/api.http.po
  docs/locale/ru/LC_MESSAGES/api.models.channel.po
  docs/locale/ru/LC_MESSAGES/api.models.guild.po
  docs/locale/ru/LC_MESSAGES/api.models.message.po
  docs/quickstart.rst
  interactions/api/http/channel.py
  interactions/api/http/guild.py
  interactions/api/http/interaction.py
  interactions/api/http/interaction.pyi
  interactions/api/models/gw.py
  interactions/api/models/gw.pyi
  interactions/client/bot.py
  interactions/client/bot.pyi
  interactions/client/decor.py
  interactions/client/decor.pyi
  interactions/client/models/command.py
Labels: documentation, enhancement, breaking, priority

#762 refactor!: optimize sync behavior
  interactions/api/http/channel.py
  interactions/api/http/channel.pyi
  interactions/api/http/client.py
  interactions/api/http/client.pyi
  interactions/api/http/emoji.py
  interactions/api/http/emoji.pyi
  interactions/api/http/guild.py
  interactions/api/http/guild.pyi
  interactions/api/http/interaction.py
  interactions/api/http/interaction.pyi
  interactions/api/http/member.py
  interactions/api/http/member.pyi
  interactions/api/http/message.py
  interactions/api/http/message.pyi
  interactions/api/http/reaction.py
  interactions/api/http/reaction.pyi
  interactions/api/http/scheduledEvent.py
  interactions/api/http/scheduledEvent.pyi
  interactions/api/http/sticker.py
  interactions/api/http/sticker.pyi
  interactions/api/http/thread.py
  interactions/api/http/thread.pyi
  interactions/api/http/user.py
  interactions/api/http/user.pyi
  interactions/api/http/webhook.py
  interactions/api/http/webhook.pyi
  interactions/client/bot.py
  interactions/client/bot.pyi
  interactions/client/decor.py
  interactions/client/decor.pyi
Labels: bug, enhancement, breaking, priority

#776 refactor!: optimize sync behaviour
  interactions/api/models/role.py
  interactions/client/bot.py
  interactions/client/bot.pyi
Labels: bug, breaking, priority

#786 Fix: prevent key error
  interactions/client/bot.py
Labels: bug, priority

#784 feat: add `@func.autocomplete`
  interactions/client/bot.py
  interactions/client/bot.pyi
Labels: enhancement

#783 feat: Adding ``url`` property for getting emoji's url from the emoji's icon
  interactions/api/models/message.py
  interactions/api/models/message.pyi
Labels: enhancement

#774 feat: ability to suppress embeds on message edit
  interactions/api/models/message.py
  interactions/api/models/message.pyi
Labels: documentation, enhancement

#796 fix!: fix en locales
  interactions/client/enums.py
Labels: bug

#797 refactor: Add ``remove_commands`` argument for un- and reloading of extensions
  interactions/client/bot.py
  interactions/client/bot.pyi
Labels: enhancement

#794 feat: Add clone_channel method to guild
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
Labels: documentation, enhancement

#799 feat: Implement Scheduled Events via Gateway.
  interactions/api/models/gw.py
  interactions/api/models/gw.pyi
Labels: documentation, enhancement

#792 feat: Implement webhook object
  docs/api.models.rst
  docs/api.models.webhook.rst
  interactions/api/http/message.py
  interactions/api/http/webhook.py
  interactions/api/http/webhook.pyi
  interactions/api/models/__init__.py
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
  interactions/api/models/member.py
  interactions/api/models/webhook.py
  interactions/api/models/webhook.pyi
Labels: documentation, enhancement

#807 fix: Include shard/presence metadata consistency.
  interactions/api/gateway/client.py
Labels: bug

#808 feat: Add has_public_flag method to user model
  interactions/api/models/user.py
  interactions/api/models/user.pyi
Labels: enhancement
