Repository interactions-py/interactions.py, pull requests merged in 2022-04, with the labels that each got.

#686 feat: Localisation support.
  .github/FUNDING.yml
  interactions/__init__.py
  interactions/api/__init__.py
  interactions/api/gateway/heartbeat.pyi
  interactions/api/http/guild.py
  interactions/api/http/request.py
  interactions/api/models/gw.py
  interactions/api/models/member.py
  interactions/api/models/member.pyi
  interactions/api/models/message.py
  interactions/client/bot.py
  interactions/client/bot.pyi
  interactions/client/decor.py
  interactions/client/decor.pyi
  interactions/client/enums.py
  interactions/client/models/command.py
  interactions/client/models/component.py
  interactions/client/models/misc.py
Labels: bug, documentation, enhancement, priority

#697 fix!: Refix context resolution due to architecture change.
  interactions/api/gateway/client.py
Labels: bug

#696 fix: Fix remaining variable definition.
  interactions/api/http/request.py
Labels: bug

#701 fix(models)!: Fix local imports surrounding component building.
  interactions/api/models/channel.py
  interactions/api/models/gw.pyi
  interactions/api/models/member.py
  interactions/api/models/message.py
  interactions/api/models/user.pyi
Labels: bug

#645 fix: Fix webhook execution payload.
  interactions/api/http/webhook.py
Labels: bug

#653 feat: Uploading/Attaching files to channel messages
  interactions/api/http/message.py
  interactions/api/http/message.pyi
  interactions/api/http/request.py
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
  interactions/api/models/misc.py
  interactions/api/models/misc.pyi
Labels: documentation, enhancement

#699 feat: Add more image URL helpers
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
  interactions/api/models/member.py
  interactions/api/models/member.pyi
  interactions/api/models/user.py
  interactions/api/models/user.pyi
Labels: documentation, enhancement

#718 fix!: Allow `@event` usage with a name argument
  interactions/client/bot.py
  interactions/client/bot.pyi
Labels: bug

#733 feat: add py.typed file
  MANIFEST.in
  interactions/py.typed
Labels: enhancement

#740 fix!: re-apply fix for guilds property; make `name` a kwarg in `event()`
  interactions/client/bot.py
  interactions/client/bot.pyi
Labels: bug

#739 fix: properly check for guild existence in cache
  interactions/api/models/guild.py
Labels: bug

#736 Fix: allow variable optional values in command arg signatures
  interactions/api/gateway/client.py
Labels: bug

#745 fix: Fix commands not being registered properly
  interactions/client/bot.py
Labels: bug

#743 fix!: Fix changing role positions
  interactions/api/http/guild.py
  interactions/api/http/guild.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
  interactions/api/models/role.py
Labels: enhancement

#754 docs: add missing closing brackets
  docs/quickstart.rst
Labels: documentation
