Repository interactions-py/interactions.py, pull requests merged in 2022-11, with the labels that each got.

#1142 feat: Add a ``wait_for_select`` method
  interactions/api/gateway/client.py
  interactions/client/bot.py
Labels: enhancement, priority

#1147 feat: Add the voice state event
  interactions/api/gateway/client.py
  interactions/api/models/channel.py
  interactions/api/models/guild.py
  interactions/api/models/gw.py
  interactions/api/models/member.py
Labels: enhancement

#1150 refactor!: remove all unwanted `__repr__` and `__str__`
  docs/migration.rst
  interactions/api/models/channel.py
  interactions/api/models/emoji.py
  interactions/api/models/guild.py
  interactions/api/models/member.py
  interactions/api/models/user.py
Labels: bug, enhancement, good first issue

#1112 docs: Huge Docs revamp
  docs/api.cache.rst
  docs/api.dispatch.rst
  docs/api.enums.rst
  docs/api.error.rst
  docs/api.gateway.rst
  docs/api.http.rst
  docs/api.models.rst
  docs/api.rst
  docs/conf.py
  docs/context.rst
  docs/events.rst
  docs/faq.rst
  docs/models.rst
  docs/quickstart.rst
  docs/utils.get.rst
  docs/utils.rst
  docs/utils.utils.rst
  interactions/api/cache.py
  interactions/api/dispatch.py
  interactions/api/error.py
  interactions/api/gateway/client.py
  interactions/api/gateway/heartbeat.py
  interactions/api/models/audit_log.py
  interactions/api/models/channel.py
  interactions/api/models/emoji.py
  interactions/api/models/guild.py
  interactions/api/models/gw.py
  interactions/api/models/member.py
  interactions/api/models/message.py
  interactions/api/models/misc.py
  interactions/api/models/presence.py
  interactions/api/models/role.py
  interactions/api/models/team.py
  interactions/api/models/user.py
  interactions/api/models/webhook.py
  interactions/client/bot.py
  interactions/client/context.py
  interactions/client/models/command.py
  interactions/client/models/component.py
  interactions/client/models/misc.py
  interactions/utils/utils.py
Labels: documentation

#1160 feat: add new error codes
  interactions/api/error.py
Labels: enhancement

#1154 refactor(automod ): Add new triggers, fix create rule endpoint
  interactions/api/http/guild.py
  interactions/api/models/misc.py
Labels: bug, enhancement

#1171 feat: Adding `files` support for file sending in context
  interactions/api/http/interaction.py
  interactions/client/context.py
Labels: enhancement

#1169 fix: Fix cache KeyError
  interactions/utils/dict_caches.py
Labels: bug

#1173 feat(channel): Add new overwrite helper methods
  interactions/api/models/channel.py
Labels: documentation, enhancement

#1175 feat: add `locale` and `guild_locale` to context
  interactions/client/context.py
Labels: enhancement

#1177 docs: Add source code view to docs
  docs/conf.py
Labels: documentation

#1126 refactor!: use `attrs.asdict` as a way to get json data of the object
  interactions/api/gateway/client.py
  interactions/api/models/channel.py
  interactions/api/models/guild.py
  interactions/api/models/message.py
  interactions/api/models/presence.py
  interactions/api/models/webhook.py
  interactions/client/bot.py
  interactions/client/models/command.py
  interactions/client/models/component.py
  interactions/utils/attrs_utils.py
  interactions/utils/attrs_utils.pyi
Labels: enhancement

#1161 docs: rework the docs to showcase when specific methods have been added
  .github/PULL_REQUEST_TEMPLATE.md
  docs/api.http.rst
  docs/api.models.audit_log.rst
  docs/api.models.webhook.rst
  docs/migration.rst
  docs/utils.abc.context_managers.rst
  docs/utils.abc.iterators.rst
  docs/utils.abc.rst
  docs/utils.get.rst
  docs/utils.rst
  interactions/api/models/audit_log.py
  interactions/api/models/channel.py
  interactions/api/models/emoji.py
  interactions/api/models/guild.py
  interactions/api/models/gw.py
  interactions/api/models/member.py
  interactions/api/models/message.py
  interactions/api/models/misc.py
  interactions/api/models/role.py
  interactions/api/models/team.py
  interactions/api/models/user.py
  interactions/api/models/webhook.py
  interactions/client/bot.py
  interactions/client/context.py
  interactions/client/enums.py
  interactions/client/models/command.py
  interactions/utils/__init__.py
  interactions/utils/abc/base_context_managers.py
  interactions/utils/abc/base_iterators.py
  interactions/utils/dict_caches.py
  interactions/utils/get.py
  interactions/utils/missing.py
  interactions/utils/utils.py
Labels: documentation, enhancement

#1181 feat: add defered_ephemeral property
  interactions/client/context.py
Labels: documentation, enhancement
