Repository interactions-py/interactions.py, pull requests merged in 2022-03, with the labels that each got.

#531 feat(message): add helper methods to `Embed`
  .pre-commit-config.yaml
  interactions/api/models/message.py
  interactions/api/models/message.pyi
Labels: wontfix

#603 chore: pre-release 4.1.1-beta.1
  .github/ISSUE_TEMPLATE/custom---miscellaneous.md
  .github/ISSUE_TEMPLATE/report-bug.yml
  .github/ISSUE_TEMPLATE/request-feature.md
  .github/ISSUE_TEMPLATE/request-feature.yml
  .pre-commit-config.yaml
  interactions/api/gateway.py
  interactions/api/http.py
  interactions/api/models/member.py
  interactions/api/models/member.pyi
  interactions/api/models/message.py
  interactions/api/models/message.pyi
  interactions/base.py
  interactions/client.py
  interactions/context.py
  interactions/ext/base.py
  interactions/ext/version.py
  interactions/models/component.py
Labels: documentation, enhancement, breaking, priority

#612 fix: add banner_color to User model
  interactions/api/models/user.py
  interactions/api/models/user.pyi
Labels: documentation, enhancement, good first issue

#634 feat: ``bot.guilds`` property
  interactions/client.py
  interactions/client.pyi
Labels: enhancement

#625 fix(channel): implement permission overwrites
  docs/api.models.flags.rst
  docs/api.models.intents.rst
  docs/api.models.rst
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
Labels: documentation, enhancement

#602 refactor: reorganize http endpoints
  docs/api.http.rst
  interactions/api/gateway.py
  interactions/api/gateway.pyi
  interactions/api/http.py
  interactions/api/http/__init__.py
  interactions/api/http/channel.py
  interactions/api/http/channel.pyi
  interactions/api/http/client.py
  interactions/api/http/client.pyi
  interactions/api/http/emoji.py
  interactions/api/http/emoji.pyi
  interactions/api/http/guild.py
  interactions/api/http/guild.pyi
  interactions/api/http/interaction.py
  interactions/api/http/interaction.pyi
  interactions/api/http/limiter.py
  interactions/api/http/limiter.pyi
  interactions/api/http/member.py
  interactions/api/http/member.pyi
  interactions/api/http/message.py
  interactions/api/http/message.pyi
  interactions/api/http/reaction.py
  interactions/api/http/reaction.pyi
  interactions/api/http/request.py
  interactions/api/http/request.pyi
  interactions/api/http/route.py
  interactions/api/http/route.pyi
  interactions/api/http/scheduledEvent.py
  interactions/api/http/scheduledEvent.pyi
  interactions/api/http/sticker.py
  interactions/api/http/sticker.pyi
  interactions/api/http/thread.py
  interactions/api/http/thread.pyi
  interactions/api/http/user.py
  interactions/api/http/user.pyi
  interactions/api/http/webhook.py
  interactions/api/http/webhook.pyi
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
  interactions/api/models/gw.pyi
  interactions/api/models/member.pyi
  interactions/api/models/message.pyi
  interactions/api/models/role.py
  interactions/api/models/role.pyi
  interactions/api/models/user.py
  interactions/client.py
  interactions/client.pyi
  interactions/context.pyi
Labels: enhancement, pending, breaking, priority

#492 feat: Add helper methods to the gw member model
  interactions/api/gateway.py
  interactions/api/models/gw.py
  interactions/api/models/gw.pyi
  interactions/api/models/member.py
  interactions/api/models/member.pyi
Labels: enhancement

#633 feat: implement magic methods
  interactions/api/gateway.py
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
  interactions/api/models/gw.py
  interactions/api/models/gw.pyi
  interactions/api/models/member.py
  interactions/api/models/member.pyi
  interactions/api/models/message.py
  interactions/api/models/message.pyi
  interactions/api/models/user.py
  interactions/api/models/user.pyi
  interactions/models/component.py
Labels: enhancement

#600 feat(guild, channel): implement new helper methods
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
Labels: documentation

#675 feat: implement ``get_all_members`` helper methods
  interactions/api/models/channel.py
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
Labels: documentation, enhancement

#635 refactor: reflect class attributes when editing the parent's children.
  interactions/api/models/channel.py
  interactions/api/models/guild.py
  interactions/api/models/member.py
  interactions/api/models/message.py
  interactions/api/models/role.py
Labels: enhancement

#672 fix!: constant command synchronization even without changes on the command
  interactions/client.py
Labels: bug
