Repository interactions-py/interactions.py, pull requests merged in 2022-01, with the labels that each got.

#422 Fix/autocomplete doc
  interactions/client.py
Labels: documentation

#421 fix: Stop configuring logging
  interactions/api/dispatch.py
  interactions/api/gateway.py
  interactions/api/http.py
  interactions/client.py
  interactions/context.py
Labels: pending, breaking

#420 feat: add member permissions
  interactions/__init__.py
  interactions/api/gateway.py
  interactions/api/gateway.pyi
  interactions/api/models/__init__.py
  interactions/api/models/flags.py
  interactions/api/models/intents.py
  interactions/api/models/member.py
  interactions/api/models/member.pyi
  interactions/client.py
  interactions/client.pyi
Labels: enhancement, pending

#418 feat: implement new functions
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
  interactions/api/models/member.py
  interactions/api/models/member.pyi
  interactions/api/models/message.py
  interactions/api/models/message.pyi
  interactions/api/models/presence.py
  interactions/api/models/role.py
  interactions/api/models/role.pyi
  interactions/context.py
  interactions/models/component.py
Labels: documentation, enhancement, question, pending

#423 fix(gateway,component): SelectMenu parse per SelectOption
  interactions/api/gateway.py
  interactions/models/component.py
Labels: bug, enhancement
