Repository interactions-py/interactions.py, pull requests merged in 2022-12, with the labels that each got.

#1146 refactor: allow stacking extension decorators
  interactions/client/bot.py
Labels: bug, enhancement

#767 feat: Implement barebones Server Subscriptions support.
  interactions/api/error.py
  interactions/api/models/audit_log.py
  interactions/api/models/guild.py
  interactions/api/models/gw.py
  interactions/api/models/message.py
  interactions/api/models/role.py
Labels: documentation, enhancement

#1190 feat: Implement `created_at` property for models
  interactions/api/models/channel.py
  interactions/api/models/emoji.py
  interactions/api/models/guild.py
  interactions/api/models/message.py
  interactions/api/models/role.py
  interactions/api/models/team.py
  interactions/api/models/user.py
  interactions/api/models/webhook.py
Labels: enhancement

#1191 fix: `Message.referenced_message` returns wrong data
  interactions/api/models/message.py
Labels: documentation, enhancement

#1188 docs: remove return type from send&edit methods
  interactions/client/context.py
Labels: documentation

#1193 refactor: add missed fields for Channel and Tags
  interactions/api/models/channel.py
Labels: enhancement

#1189 refactor: add missed http clients and some optimizing
  interactions/api/gateway/ratelimit.py
  interactions/api/models/gw.py
  interactions/client/context.py
Labels: enhancement

#1196 fix: Pass HTTPClient to all objects when using get() with cache.
  interactions/api/models/message.py
  interactions/utils/get.py
Labels: bug

#1204 fix: few bugs with object serialization
  interactions/api/gateway/client.py
  interactions/utils/attrs_utils.py
Labels: bug

#1203 feat: Implement barebones Linked Roles support.
  interactions/api/http/client.py
  interactions/api/models/team.py
Labels: enhancement

#1202 feat: implement modify guild emoji helper
  interactions/api/models/emoji.py
  interactions/api/models/guild.py
Labels: enhancement
