Repository interactions-py/interactions.py, pull requests merged in 2022-10, with the labels that each got.

#1108 fix: fix incorrect typehint in audit log helper method
  interactions/api/models/guild.py
Labels: bug, documentation, enhancement

#1098 feat: Implement helper methods for invites
  interactions/api/http/invite.py
  interactions/api/models/guild.py
Labels: enhancement

#1115 fix: Reimplement manual sharding/presence, fix forum tag implementation
  interactions/api/gateway/client.py
  interactions/api/http/channel.py
  interactions/api/http/thread.py
  interactions/client/bot.py
Labels: enhancement

#836 feat: Implement barebones Select Menus for other supporting types
  interactions/api/gateway/client.py
  interactions/client/bot.py
  interactions/client/enums.py
  interactions/client/models/component.py
Labels: documentation, enhancement

#1060 refactor!: Replace the Color class with an enum
  docs/migration.rst
  interactions/api/models/misc.py
Labels: breaking, on hold

#1104 feat: Implement guild_join event
  interactions/api/gateway/client.py
Labels: on hold
