Repository interactions-py/interactions.py, pull requests merged in 2022-02, with the labels that each got.

#428 feat: create basic functionality for Extensions
  interactions/client.py
  interactions/client.pyi
Labels: documentation, enhancement, pending, breaking, priority

#429 feat: allow passing a command name in autocomplete decorator
  interactions/client.py
  interactions/client.pyi
Labels: documentation, enhancement, pending

#456 feat: implement new helper methods
  docs/faq.rst
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
  interactions/api/models/message.py
  interactions/api/models/message.pyi
  interactions/context.py
  interactions/context.pyi
Labels: enhancement

#468 fix!: correct guild_scheduled_event request and json serialisation in helper methods.
  interactions/api/http.py
  interactions/api/models/guild.py
Labels: pending

#474 fix!: rename method name `get_application_command`
  interactions/api/http.py
  interactions/client.py
Labels: enhancement, breaking

#427 feat: Implement new Permissions v2.01.
  interactions/api/models/gw.py
  interactions/api/models/gw.pyi
  interactions/enums.py
  interactions/models/command.py
Labels: documentation, enhancement, priority

#447 feat: add Get Guild Audit Log to `HTTPClient`
  interactions/api/http.py
Labels: documentation, enhancement, pending

#484 feat: implement ctx.custom_id and ctx.label properties
  interactions/context.py
Labels: enhancement

#486 fix!: prevent creating a payload for not present values in ComponentContext
  interactions/context.py
Labels: bug, enhancement, pending

#477 fix: passing command names in autocomplete decorator
  interactions/client.py
  interactions/client.pyi
  interactions/context.py
Labels: enhancement

#500 fix!: remove `._json` from dict object when editing comnponents
  interactions/context.py
Labels: bug

#461 docs: enhance the quickstart
  .pre-commit-config.yaml
  docs/_static/OAuth2_left.png
  docs/_static/applications_left.png
  docs/_static/build_a_bot.png
  docs/_static/copy_guild_id.png
  docs/_static/create_application.png
  docs/_static/dev_mode_discord.png
  docs/_static/scopes_OAuth2.png
  docs/faq.rst
  docs/quickstart.rst
Labels: documentation, enhancement

#502 fix!: command synchronization and command Exceptions
  interactions/client.py
Labels: bug

#503 docs: add modals to the quickstart
  docs/_static/modal_popup.png
  docs/quickstart.rst
Labels: documentation

#530 docs: Redocument CommandContext
  interactions/context.py
Labels: documentation

#529 refactor: create an extra function for command payload checking
  interactions/client.py
  interactions/client.pyi
Labels: enhancement

#451 refactor: make the Gateway optimised in connection and dispatch.
  interactions/api/gateway.py
  interactions/api/gateway.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
  interactions/api/models/gw.py
  interactions/client.py
  interactions/client.pyi
  simple_bot.py
Labels: documentation, enhancement, priority

#526 refactor: extract component building into seperate function
  interactions/api/models/channel.py
  interactions/api/models/member.py
  interactions/api/models/message.py
  interactions/context.py
  interactions/models/component.py
Labels: enhancement

#479 feat: Abstract `modify` method in data models for simplified usage.
  interactions/api/models/channel.py
  interactions/api/models/channel.pyi
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
Labels: enhancement

#544 fix!: prevent exception for non-chat-input commands when no description is present
  interactions/client.py
Labels: bug

#556 Fix!: prevent conflict between slot and function name in guild.py
  interactions/api/models/guild.py
  interactions/api/models/guild.pyi
Labels: bug, breaking

#559 fix!: Correct gateway command and subcommand dispatching
  interactions/api/dispatch.py
  interactions/api/gateway.py
  interactions/api/gateway.pyi
  interactions/api/models/gw.py
Labels: bug, pending, breaking, priority
