Repository interactions-py/interactions.py, pull requests merged in 2023-04, with the labels that each got.

#1294 fix: bugs when creating forum post
  interactions/api/http/request.py
  interactions/api/models/channel.py
Labels: bug

#1333 docs: add more specific docs for linux users using voice
  docs/src/Guides/23 Voice.md
Labels: documentation

#1341 V5.1.0
  .github/workflows/python-publish.yml
  LICENSE
  docs/src/API Reference/API Reference/models/Internal/active_voice_state.md
  docs/src/Guides/02 Creating Your Bot.md
  docs/src/Guides/03 Creating Commands.md
  docs/src/Guides/04 Context Menus.md
  docs/src/Guides/05 Components.md
  docs/src/Guides/08 Converters.md
  docs/src/Guides/10 Events.md
  docs/src/Guides/100 Migration From D.py.md
  docs/src/Guides/20 Extensions.md
  docs/src/Guides/23 Voice.md
  docs/src/Guides/24 Localisation.md
  docs/src/Guides/25 Error Tracking.md
  docs/src/Guides/26 Prefixed Commands.md
  docs/src/Guides/90 Example.md
  docs/src/Guides/98 Migration from 4.X.md
  docs/src/Guides/index.md
  docs/src/changelog.md
  interactions/__init__.py
  interactions/api/http/http_client.py
  interactions/api/http/http_requests/channels.py
  interactions/api/http/http_requests/emojis.py
  interactions/api/http/http_requests/guild.py
  interactions/api/http/http_requests/interactions.py
  interactions/api/http/http_requests/members.py
  interactions/api/http/http_requests/messages.py
  interactions/api/http/http_requests/reactions.py
  interactions/api/http/http_requests/scheduled_events.py
  interactions/api/http/http_requests/stickers.py
  interactions/api/http/http_requests/threads.py
  interactions/api/http/http_requests/users.py
  interactions/api/http/http_requests/webhooks.py
  interactions/client/client.py
  interactions/client/const.py
  interactions/client/smart_cache.py
  interactions/ext/debug_extension/debug_application_cmd.py
  interactions/models/__init__.py
  interactions/models/discord/asset.py
  interactions/models/discord/channel.py
  interactions/models/discord/enums.py
  interactions/models/discord/guild.py
  interactions/models/discord/message.py
  interactions/models/discord/role.py
  interactions/models/discord/scheduled_event.py
  interactions/models/discord/sticker.py
  interactions/models/discord/thread.py
  interactions/models/discord/user.py
  interactions/models/discord/user.pyi
  interactions/models/internal/__init__.py
  interactions/models/internal/application_commands.py
  interactions/models/internal/command.py
  interactions/models/internal/cooldowns.py
  pyproject.toml
  setup.py
  tests/test_bot.py
Labels: pending

#1360 feat: format ratelimit messages with major params
  interactions/api/http/http_client.py
  interactions/api/http/route.py
Labels: enhancement
