Repository interactions-py/interactions.py, pull requests merged in 2023-02, with the labels that each got.

#1245 refactor(context): allow edit message from modal interaction
  interactions/client/context.py
Labels: bug, enhancement

#1243 fix: `client`, `command` and `extension` are missed in `on_command`
  interactions/api/gateway/client.py
  interactions/client/models/command.py
Labels: bug

#1273 feat: add global autocomplete
  interactions/__init__.py
  interactions/client/client.py
  interactions/models/__init__.py
  interactions/models/internal/__init__.py
  interactions/models/internal/application_commands.py
  interactions/models/internal/extension.py
  main.py
Labels: enhancement

#1282 fix(member): cannot remove member from voice channel
  interactions/api/models/member.py
Labels: bug

#1287 feat: implement console ext
  docs/src/Guides/98 2.x Migration.md
  docs/src/extra.css
  docs/src/index.md
  interactions/ext/console.py
  pyproject.toml
  setup.py
Labels: enhancement
