Repository interactions-py/interactions.py, pull requests merged in 2023-01, with the labels that each got.

#1217 fix: Error starting when using scope param in command decorator
  interactions/client/bot.py
Labels: bug

#1212 fix(attrs): add factory value to interaction resolved data
  interactions/client/models/misc.py
Labels: bug

#1215 feat: Add `channel` & `guild` properties for `VoiceState`
  interactions/api/models/gw.py
Labels: enhancement

#1221 feat: Add support for the event `GUILD_AUDIT_LOG_ENTRY_CREATE`
  interactions/api/models/gw.py
Labels: enhancement

#1220 fix: Warns user that the bot is not in guild than rather fails
  interactions/client/bot.py
Labels: bug

#1222 docs: add missed fields for the `GuildAuditLogEntry`
  interactions/api/models/audit_log.py
  interactions/api/models/gw.py
Labels: documentation

#1209 refactor!: Change type of permissions attrs to `Permissions`
  interactions/api/models/channel.py
  interactions/api/models/guild.py
  interactions/api/models/message.py
  interactions/api/models/misc.py
  interactions/api/models/role.py
  interactions/client/context.py
Labels: bug, enhancement

#1224 feat!: Implement support for the `guild_audit_log_entry_create` event
  interactions/api/events/__init__.py
  interactions/api/events/discord.py
  interactions/api/events/processors/guild_events.py
  interactions/client/client.py
  interactions/models/discord/enums.py
Labels: enhancement

#1207 feat: Add helpers for role connection
  interactions/client/bot.py
Labels: enhancement

#1208 feat: Add support for age-restricted commands
  interactions/client/bot.py
  interactions/client/decor.py
  interactions/client/models/command.py
Labels: enhancement

#1219 refactor(context): move `delete` to base context
  interactions/client/context.py
Labels: enhancement

#1201 feat: Implement own `IntEnum` & `StrEnum`
  interactions/api/gateway/client.py
  interactions/api/models/audit_log.py
  interactions/api/models/channel.py
  interactions/api/models/flags.py
  interactions/api/models/guild.py
  interactions/api/models/message.py
  interactions/api/models/misc.py
  interactions/api/models/presence.py
  interactions/api/models/team.py
  interactions/api/models/webhook.py
  interactions/client/enums.py
  interactions/ext/error.py
  interactions/ext/version.py
  interactions/utils/get.py
  interactions/utils/get.pyi
Labels: bug, enhancement

#1239 fix: check `Client._http` is not a string before logout
  interactions/client/bot.py
Labels: bug

#1241 feat: add support for multiple images in an embed
  interactions/models/discord/embed.py
  main.py
Labels: enhancement

#1244 docs: add missed docs for role connection metadata
  interactions/api/models/team.py
Labels: documentation

#1252 feat: add member flags
  interactions/api/models/flags.py
  interactions/api/models/member.py
Labels: enhancement

#1253 docs: remove extra brackets in audit log entry
  interactions/api/models/audit_log.py
  interactions/api/models/gw.py
Labels: documentation

#1251 feat: Add member flags
  interactions/models/discord/__init__.py
  interactions/models/discord/enums.py
  interactions/models/discord/user.py
Labels: enhancement

#1250 Ratelimit tracebacks
  interactions/api/http/http_client.py
  interactions/client/client.py
  interactions/client/const.py
  interactions/ext/debug_extension/__init__.py
Labels: enhancement
